#theme: jekyll-theme-minimal
remote_theme: aidewoode/jekyll-theme-mint
title: Adam Rohde
description: Welcome! Learn a bit about me, reach out, and keep an eye on my projects!
github:
  is_project_page: false
