theme: jekyll-theme-minimal
title: Adam Rohde
description: Welcome! Learn a bit about me, reach out, and keep an eye on my projects! [<img src="https://ucla.edu/favicon.ico" width="24">](http://directory.stat.ucla.edu/active_students/single-page/?smid=1612) [<img src="https://www.linkedin.com/favicon.ico" width="24">](https://www.linkedin.com/in/adam-rohde)  [<img src="https://github.com/favicon.ico" width="24">](https://github.com/Adam-Rohde)
logo: /images/Rohde2021-58 - Copy (2).jpg
github: false
